<%@ Page Language="C#" MasterPageFile="~/HRManger/HRMasterPage.master" AutoEventWireup="true" CodeFile="ViewShiftDetails.aspx.cs" Inherits="HRManger_ViewShiftDetails" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <table cellspacing="5" cellpadding="0" align="center" width="700"  class="border1"  >
        <tr>
             <td class="border" colspan="2" align="center"><b class="title">View ShiftDetails</b>
            </td>
        </tr>
        <tr>
            <td align="center" >
                <asp:GridView ID="GdV_ShiftDetails" runat="server" Style="position: static" AutoGenerateDeleteButton="True" Font-Names="Arial" Font-Size="9pt" OnRowDeleting="GdV_ShiftDetails_RowDeleting" OnRowCommand="GdV_ShiftDetails_RowCommand" AllowPaging="True" OnPageIndexChanging="GdV_ShiftDetails_PageIndexChanging" AutoGenerateColumns="False">
                    <Columns>
                        <asp:TemplateField>
                            <ItemTemplate>
                                <asp:LinkButton ID="LinkButton1" runat="server" CommandName="Edit" CommandArgument='<%#DataBinder.Eval(Container.DataItem,"ShiftID") %>'>Edit</asp:LinkButton>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="ShiftID" HeaderText="ShiftID" />
                        <asp:BoundField DataField="ShiftName" HeaderText="ShiftName" />
                        <asp:BoundField DataField="StartingTime" HeaderText="StartingTime" />
                        <asp:BoundField DataField="DispatchTime" HeaderText="DispatchTime" />
                        <asp:BoundField DataField="NoBatches" HeaderText="NoBatches" />
                    </Columns>
                    <RowStyle HorizontalAlign="Center" />
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>

