<%@ Page Language="C#" MasterPageFile="~/Admin/WelcomeAdmin.master" AutoEventWireup="true" CodeFile="ViewMangerDetails.aspx.cs" Inherits="Admin_ViewMangerDetails" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table align="center" cellpadding="0" cellspacing="5" class="border1" style="position: static"
        width="700">
         <tr>
            <td align="center" class="border" colspan="3" style="height: 22px">
                <b class="title">View Managers</b></td>
           
            
        </tr>
        <tr>
            <td >
            </td>
        </tr>
        <tr>
            <td  align="center">
                <asp:GridView ID="GdVManger" runat="server" Style="position: static" AutoGenerateDeleteButton="True" OnRowCommand="GdVManger_RowCommand" OnRowDeleting="GdVManger_RowDeleting">
                    <RowStyle HorizontalAlign="Center" />
                    <Columns>
                        <asp:TemplateField>
                        <ItemTemplate>
                         <asp:LinkButton ID="LinkButton1" runat="server" CommandName="Edit"  CommandArgument='<%#DataBinder.Eval(Container.DataItem,"MangerID") %>'>Edit</asp:LinkButton>
                        </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>

