<%@ Page Language="C#" MasterPageFile="~/HRManger/HRMasterPage.master" AutoEventWireup="true"
    CodeFile="View ShiftSchedul.aspx.cs" Inherits="HRManger_View_ShiftSchedul" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
   
    <table cellspacing="5" cellpadding="0" align="center" width="700" class="border1">
        <tr>
            <td class="border" colspan="2" align="center">
                <b class="title">View ShiftSchdule Details</b></td>
        </tr>
        <tr>
            <td align="center">
                <asp:GridView ID="GdV_ShiftSchedul" runat="server" AutoGenerateDeleteButton="True"
                    Style="position: static" Font-Names="Arial" Font-Size="9pt" OnRowDeleting="GdV_ShiftSchedul_RowDeleting" OnRowCommand="GdV_ShiftSchedul_RowCommand" AllowPaging="True" OnPageIndexChanging="GdV_ShiftSchedul_PageIndexChanging" AutoGenerateColumns="False">
                    <Columns>
                        <asp:TemplateField>
                            <ItemTemplate>
                                <asp:LinkButton ID="LinkButton1" runat="server" CommandName="Edit" CommandArgument='<%#DataBinder.Eval(Container.DataItem,"ShiftSchduleID") %>'>Edit</asp:LinkButton>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="ShiftSchduleID" HeaderText="ShiftSchduleID" />
                        <asp:BoundField DataField="EmpID" HeaderText="EmpID" />
                        <asp:BoundField DataField="Department" HeaderText="Department" />
                        <asp:BoundField DataField="BatchID" HeaderText="BatchID" />
                        <asp:BoundField DataField="EmpName" HeaderText="EmpName" />
                        <asp:BoundField DataField="ShiftID" HeaderText="ShiftID" />
                        <asp:BoundField DataField="RouteID" HeaderText="RouteID" />
                    </Columns>
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>
